name: UniSURFity
favicon: null
layout_spectrum: 0.6058133838232607
typography_spectrum: 0.03518805559724569
title: UniSURFity
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.13673315034247935
  lightness: 0.27153324731625617
  saturation: 0.7085784752853215
  rhythmicContrast: 0.8189411906059831
purpose: []
